INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (100001, 'aarchish', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (100002, 'aarchish', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (100003, 'aarchish', 'Learn SpringBoot', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (100004, 'aarchish', 'Learn Kotlin', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (100005, 'aarchish', 'Build SpringBoot App for Firewall Automation', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (100006, 'aarchish', 'Build KreditNote Android App', CURRENT_DATE(), false);